version: "3"

services:
  # MongoDB database service
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - hotel-network

  # Rooms Service
  rooms-service:
    build: ./rooms-service
    ports:
      - "3001:3001"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Booking Service
  booking-service:
    build: ./booking-service
    ports:
      - "3002:3002"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Customers Service
  customers-service:
    build: ./customers-service
    ports:
      - "3003:3003"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Authentication Service
  authentication-service:
    build: ./authentication-service
    ports:
      - "3004:3004"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Inventory Service
  inventory-service:
    build: ./inventory-service
    ports:
      - "3005:3005"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Payment Service
  payment-service:
    build: ./payment-service
    ports:
      - "3006:3006"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "3007:3007"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Housekeeping Service
  housekeeping-service:
    build: ./housekeeping-service
    ports:
      - "3008:3008"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Loyalty Service
  loyalty-service:
    build: ./loyalty-service
    ports:
      - "3009:3009"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Pricing Service
  pricing-service:
    build: ./pricing-service
    ports:
      - "3010:3010"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Feedback Service
  feedback-service:
    build: ./feedback-service
    ports:
      - "3011:3011"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3012:3012"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Event Management Service
  event-management-service:
    build: ./event-management-service
    ports:
      - "3013:3013"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Analytics Service
  analytics-service:
    build: ./analytics-service
    ports:
      - "3014:3014"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Room Automation Service
  room-automation-service:
    build: ./room-automation-service
    ports:
      - "3015:3015"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Guest Service
  guest-service:
    build: ./guest-service
    ports:
      - "3016:3016"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # Staff Management Service
  staff-management-service:
    build: ./staff-management-service
    ports:
      - "3017:3017"
    networks:
      - hotel-network
    depends_on:
      - mongo

  # CRM Service
  crm-service:
    build: ./crm-service
    ports:
      - "3018:3018"
    networks:
      - hotel-network
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  hotel-network:
    driver: bridge
